quarkus.datasource.db-kind = postgresql 

%prod.quarkus.datasource.username = hibernate
%prod.quarkus.datasource.password = hibernate
%prod.quarkus.datasource.reactive.url = vertx-reactive:postgresql://localhost/products 

%prod.quarkus.hibernate-orm.schema-management.strategy=


mp.messaging.incoming.sales.topic=sale-requests
mp.messaging.incoming.sales.auto.offset.reset=earliest

quarkus.kafka.devservices.topic-partitions.sale-requests=3

